### ISSUE TITLE
OnComplete() is not called for tween inside Sequence.

### ISSUE THREAD

**Issue by Decavoid** [Demigiant/dotween#31] opened 2015-06-18 15:46 UTC
**What steps will reproduce the problem?**

```
int dummy = 0;
float duration1 = 0.001f;
float duration2 = 0.0010001f;
bool isTweenCompleted = false;
Sequence itemSequence = DOTween.Sequence()
    .AppendInterval(duration1)
    .Append(DOTween.To(() => 0, i => dummy = i, 20, duration2)
        .OnComplete(() =>
        {
            Debug.Log("OnComplete tween");
            isTweenCompleted = true;
        }))
    .OnComplete(() => { Debug.Log("OnComplete sequence, " + (isTweenCompleted ? "ok" : "BUG")); });
```

**What is the expected output? What do you see instead?**

Expected:
OnComplete tween
OnComplete sequence, ok

Actual result:
OnComplete sequence, BUG

**What version of the product are you using?**
DOTween v1.0.770 [Release build]

Bug occurs for some values of `duration2`.

**Comment by gcoope** [comment] 2015-06-23 14:45
I managed to reach the expected outcome by replacing the OnComplete with an AppendCallback on the sequence. I haven't tested if this works if you appended another tween to the end of the AppendCallback.

``` C#
int dummy = 0;
float duration1 = 0.001f;
float duration2 = 0.0010001f;
bool isTweenCompleted = false;
Sequence itemSequence = DOTween.Sequence()
    .AppendInterval(duration1)
        .Append(DOTween.To(() => 0, i => dummy = i, 20, duration2))
            .AppendCallback(()=> {
                Debug.Log("OnComplete tween");
                isTweenCompleted = true;
            })
        .OnComplete(() => { Debug.Log("OnComplete sequence, " + (isTweenCompleted ? "ok" : "BUG")); });
```

**Comment by alryazanov** [comment] 2015-06-24 14:19
+1
Recently I received an unexpected behavior that some OnComplete events in Sequence not called

**Comment by mysl1212** [comment] 2015-12-08 08:36
any fix or solutions? also have this problem:when tweens in a sequence have a very short duration,the last tween's oncomplete won't be called

**Comment by Demigiant** [comment] 2015-12-08 10:41
Hey, can you try [this last version 1.1.140](http://dotween.demigiant.com/tmp/DOTween_1_1_140.zip) and let me know? It should've fixed this issue.

**Comment by mysl1212** [comment] 2015-12-09 01:56
yes,it works,thank you~

**Comment by mysl1212** [comment] 2015-12-09 02:14
but i put the latest source code to my project ,the problem is still there   :(
i prefer source code to dlls

**Comment by Demigiant** [comment] 2015-12-09 09:36
That is weird. You tried both the DLL and the source in the same project, and only the source is working? I did update the source too, as usual.

**Comment by rubit0** [comment] 2015-12-16 03:02
I bumped today into the same problem, wasted 2 hours till I found out and fixed it by splitting the Sequence into several Tweeners and handling code flow via a simple bool.

I hope this will be fixed in the future since sequences are wonderfully elegant!

**Comment by Demigiant** [comment] 2015-12-16 10:56
Hey Ruben! :)
Can you try to 1.1.140 version I posted a few posts above yours? That should've fixed the issue.

**Comment by rubit0** [comment] 2015-12-16 11:25
That 1.1.140 Version that was posted before didn't worked for me, well at least on my current project but I will investigate in it on a fresh project. Maybe my current project was simply messed up or something.
Thanks!

**Comment by Demigiant** [comment] 2015-12-16 11:37
Thanks! Let me know. I added a fail-safe routine, and on all my test projects it works.

**Closed as completed** 2016-10-17 23:36 UTC
